frase=('Curso em Vídeo Python')
print(frase)
print(frase[3])
print(frase[3:7])
print(frase[9:21:2])
print(frase[:15])
print(frase[15:])
print(frase[9::3])
#len()
print(frase.count('o',0,13))
print(frase.find('deo'))
print(frase.find('android'))
print('Curso' in frase)
print(frase.replace('Python','Android'))
print(frase.upper())
print(frase.lower())
print(frase.capitalize())
print(frase.title())
frase2=('   Aprenda Python  ')
print(frase2)
print(frase2.strip())
print(frase2.rstrip())
print(frase2.lstrip())
print(frase.split())
print('-'.join(frase))